### ISSUE TITLE
Add TypeScript Definitions

### ISSUE THREAD

**Issue by imran-ebi** [ZeeCoder/use-resize-observer#17]
I saw that the type definitions for TypeScript was removed due to #12. This is probably due to the not-so-good type definitions I created in a PR. My bad. However, we can still add type definitions using TypeScript's `tsconfig.json`. There is a setting called `declaration` that needs to be applied in it like here: https://github.com/frankwallis/react-slidedown/blob/master/tsconfig.json. TypeScript will then generate the TypeDefinitions automatically for us when we run its compiler.

**Comment by ZeeCoder** [comment]
It was specifically because of how this turned out:
https://github.com/ZeeCoder/use-resize-observer/pull/13#issuecomment-513493984

I'm not comfortable adding TS definitions back in without knowing anything about TS myself, as I have no way of knowing whether anything TS-related that a lib user proposes makes sense or not, or whether someone else will come later and try to correct it to something that I yet again have no way to check myself.
 
I'm sure there's a way to use a 3rd party lib in a TS codebase without the lib being written in TS or having types explicitly exported.

I think I'll only add TS types here when I learn it in the future and then I'll just rewrite the whole source in it.
