### ISSUE TITLE
Padding not taken into account ?

### ISSUE THREAD

**Issue by abernierloreal** [ZeeCoder/use-resize-observer#57]
A little question,

Is that normal that padding isn't taken into account in the returned `height` value ?

NB: I have the rule `* {box-sizing:border-box;}` if ever it matters

Thank you

**Comment by ZeeCoder** [comment]
The library uses `ResizeObserver.observe()` without any extra options, which means it observes the content-box according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/observe)

I think this issue is sort of related to [this PR](https://github.com/ZeeCoder/use-resize-observer/pull/31).

Once an option is added for that, it will handle your use-case, but it's not possible at the moment.
