### ISSUE TITLE
onResize is not called on mount

### ISSUE THREAD

**Issue by lishine** [ZeeCoder/use-resize-observer#88]
onResize is not called on mount in case when useResizeObserver is given an external ref
```ts
const ref = useRef<HTMLDivElement | null>(null)
```

```ts
	useResizeObserver({
		onResize: ({ height = 0, width = 0 }) => {
			setPanelHeight(height)
			setPanelWidth(width)
		},
		ref,
	})
```

vs

```ts
	const { ref } = useResizeObserver({
		onResize: ({ height = 0, width = 0 }) => {
			setPanelHeight(height)
			setPanelWidth(width)
		},
	})
```

**Comment by ZeeCoder** [comment]
Interesting, depending on the exact circumstances this may or may not work, since we cannot detect (and react to) changes in ref.
(It would help a lot if you could reproduce in a [codesandbox](https://codesandbox.io/).)

The ref you use in the second example works, because it's a ref callback, and so every time the elements changes (or set with a delay), the hook is notified.

I recommend either sticking to the second pattern, or if you have your own ref that you have to use, to [merge the callback ref](https://github.com/gregberge/react-merge-refs) you get from the hook with it, before setting it on the element.

**Comment by prbxr** [comment]
I indeed now start using the merge callback pattern, but would rather not to.
Wouldn't you think it could be implemented such that useResizeObserver will include mount triggered useEffect(()=>{},[]) to call the provided to the hook callback ?

**Comment by lishine** [comment]
I indeed now start using the merge callback pattern, but would rather not to.
Wouldn't you think it could be implemented such that useResizeObserver will include mount triggered useEffect(()=>{},[]) to call the provided to the hook callback ?

**Comment by ZeeCoder** [comment]
I can't reproduce this issue, see [this codesandbox](https://codesandbox.io/s/relaxed-lake-s8wl9t?file=/src/App.js) of an example where I pass in a ref to the hook, and onResize is called on the initial mount as well as on resizes.
