### ISSUE TITLE
Basic usage is not working

### ISSUE THREAD

**Issue by andyperlitch** [ZeeCoder/use-resize-observer#92]
Hello there! I'm trying to get the absolute minimum usage example working, and am running into an issue. I have tried on linux and mac, on firefox and chrome, and cannot get it to work.

Here is a code sandbox reproducing it:
https://codesandbox.io/s/exciting-surf-uos1hs?file=/src/App.js

You will see that the `onResize` function is being called with the new size, however, the `width` variable returned by `useResizeObserver` is not getting updated.

**Comment by ZeeCoder** [comment]
Hi!
Thank you very much for the reproduction.

There seems to be 2 issues here:
- Since you're passing in "onResize", you're actually opting out of the width/height responses. This is because the callback allows you to opt out of rendering altogether.
- The width/height responses doesn't seem to work with react 18 anyway, and are stuck at the default "1x1" for me. :man_shrugging: 

I'm working on an update to make the hook compatible, so this'll be a good test case.

**Comment by andyperlitch** [comment]
I'm so glad my repro helped you out! Good to know about the `onResize` function.
